#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Title:----------(type name of code here)

Created on Mon Jul  1 13:13:23 2019

Author:---------Ty Sterling
Contact:--------ty.sterling@colorado.edu
Instituion:-----University of Colorado Boulder
Department:-----Material Science & Physics

Description: (type code or project description here!)

"""

import numpy as np
import matplotlib.pyplot as plt
import sys
import os

filename = 'last_run.csv'

if len(sys.argv) > 2:
    print('\nERROR: only takes one argument, the .csv file\n')
    exit()
elif len(sys.argv) == 2:
    if not os.path.exists(sys.argv[1]):
        print('\nERROR: file \'{}\' not found\n'.format(sys.argv[1]))
        exit()
    else:
        filename = sys.argv[1]

try:
    grid = np.loadtxt(filename)
except:
    print('\nERROR: something seems wrong with the data\n')
    exit()


# shift all non-zero data to a large number for use with imshow
mask = (grid != 0).astype(int)*7500

# plot it all
fig, ax = plt.subplots()
ax.imshow(grid+mask,cmap='CMRmap')
for axis in ['top','bottom','left','right']:
  ax.spines[axis].set_linewidth(1.5)
ax.minorticks_on()
ax.tick_params(which='both', width=1)
ax.tick_params(which='major', length=5)
ax.tick_params(which='minor', length=3, color='k')
ax.set_xlabel('X-coord',labelpad=4,fontweight='normal',
              fontsize='large')
ax.set_ylabel('Y-coord',labelpad=3,fontweight='normal',
              fontsize='large')

fig.suptitle('N = {}, Grid = {}x{}'.format(25000,500,500),y=0.95)

plt.savefig('dendrite.png',format='png',dpi=300,bbox_inches='tight')

plt.show()

