#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Title:---------- GrowDendrite - Plotting tool

Created on Mon Jul  1 13:13:23 2019

Author:---------Ty Sterling
Contact:--------ty.sterling@colorado.edu
Instituion:-----University of Colorado Boulder
Department:-----Material Science & Physics

Description: This reads a .csv file (default name below or takes it as argument)
    and creates a plot.
"""

import numpy as np
import matplotlib.pyplot as plt
import sys
import os

binning = 25
filename = 'arrival_rate.csv'

if len(sys.argv) > 2:
    print('\nERROR: only takes one argument, the .csv file\n')
    exit()
elif len(sys.argv) == 2:
    if not os.path.exists(sys.argv[1]):
        print('\nERROR: file \'{}\' not found\n'.format(sys.argv[1]))
        exit()
    else:
        filename = sys.argv[1]
try:
    arrivals = np.loadtxt(filename)
except:
    print('\nERROR: something seems wrong with the data\n')
    exit()

num_particles = len(arrivals)
particles = np.arange(1,num_particles+1)

nbins = num_particles//binning
avg_arrivals = np.zeros(nbins)
avg_arrivals_err = np.zeros(nbins)
bins = np.arange(1,num_particles,binning)
for i in range(nbins):
    avg_arrivals[i] = np.mean(arrivals[i*binning:(i+1)*binning])
    avg_arrivals_err[i] = np.std(arrivals[i*binning:(i+1)*binning])

# plot it all
fig, ax = plt.subplots()
fig.set_size_inches(8,4,forward=True)
fig.tight_layout(pad=4.5)

ax.plot(particles,arrivals,'o',ls='',ms=3,mfc='b',mec='k',mew='1')
ax.errorbar(bins,avg_arrivals,avg_arrivals_err,marker='o',ls='',ms=5,mfc='r',
        mec='k',mew='1',elinewidth=1,ecolor='r',zorder=10)


for axis in ['top','bottom','left','right']:
  ax.spines[axis].set_linewidth(1.5)

ax.minorticks_on()
ax.tick_params(which='both', width=1)
ax.tick_params(which='major', length=5)
ax.tick_params(which='minor', length=3, color='k')

ax.set_xlabel('Particle',labelpad=4,fontweight='normal',
              fontsize='large')
ax.set_ylabel('Arrival Time (steps)',labelpad=4,fontweight='normal',
              fontsize='large')

#fig.suptitle('N = {}, Grid = {}x{}'.format(num_particles,edge_len,edge_len),y=0.98,
#        fontsize='x-large',fontweight='bold')

#plt.savefig('arrivals.png',format='png',dpi=600,bbox_inches='tight')

plt.show()

